---
version: 1
sets:
- language: php
  bin: php
  path: jobs/v4beta1/
  __items__:
  - target: talent_list_companies
    path: php/ListCompaniesRequestPagedAllTalentListCompanies.php
  - target: talent_delete_company
    path: php/DeleteCompanyRequestTalentDeleteCompany.php
  - target: talent_create_company
    path: php/CreateCompanyRequestTalentCreateCompany.php
- language: go
  bin: go run
  path: jobs/v4beta1/
  __items__: []
