---
version: 1
sets:
- language: php
  bin: php
  path: language/v1beta2/
  __items__:
  - region_tag: language_analyze_sentiment_v1beta2
    path: php/AnalyzeSentimentRequestLanguageAnalyzeSentimentV1beta2.php
- language: go
  bin: go
  path: language/v1beta2/
  __items__:
  - region_tag: language_analyze_sentiment_v1beta2
    path: go/google.cloud.language.v1beta2.LanguageService_AnalyzeSentiment_language_analyze_sentiment_v1beta2.go
