#! /bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage: ./script/config [api_name] [api_version]"
  echo
  echo "Prints path to the GAPIC config file for [api_name] [api_version]"
fi

API_NAME="$1"
API_VERSION="$2"

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
CODE_SAMPLES_DIR="$( dirname "$SCRIPT_DIR" )"
GOOGLEAPIS_DIR="$( dirname "$CODE_SAMPLES_DIR" )"
GOOGLE_DIR="$GOOGLEAPIS_DIR/google"

GAPIC_CONFIG="$( find "$GOOGLE_DIR" -type f -name "${API_NAME}_gapic.yaml" | grep "/$API_VERSION/" )"

if [ -n "$GAPIC_CONFIG" ]; then
  echo "$GAPIC_CONFIG"
  exit 0
else
  echo "GAPIC config not found for $API_NAME $API_VERSION"
  exit 1
fi
