#! /bin/bash

if [ "$#" -ne 2 ]; then
  echo "Usage: ./script/edit [api_name] [api_version]"
  echo
  echo 'Opens the relevant GAPIC configuration file in your $EDITOR'
  echo
  echo "Your editor is set to: $EDITOR"
fi

API_NAME="$1"
API_VERSION="$2"

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

GAPIC_CONFIG="$( $SCRIPT_DIR/config "$API_NAME" "$API_VERSION" )"

if [ -n "$GAPIC_CONFIG" ]; then
	if [ -z "$EDITOR" ]; then
		echo "EDITOR environment variable not set"
		echo "Using Default Editor (vi)"
		EDITOR=vi
	fi
  $EDITOR "$GAPIC_CONFIG"
  exit 0
else
  echo "GAPIC config not found for $API_NAME $API_VERSION"
  exit 1
fi
