#! /usr/bin/env ruby

unless ARGV.length == 1
  puts "Usage: ./script/generate-test-manifest [sample directory]"
  puts
  puts "e.g. ./script/generate-test-manifest speech/"
  puts "e.g. ./script/generate-test-manifest speech/v1/"
  exit
end

require "yaml"

excluded_paths = %w[ /env/ /node_modules/ /vendor/ ]

languages = [
  { name: "php",    extension: "php", bin: "php",    samples: [] },
  { name: "python", extension: "py",  bin: "python", samples: [] },
  { name: "go",     extension: "go",  bin: "go run", samples: [] }
]

directory = ARGV.shift

Dir.chdir(directory) do
  languages.each do |language|
    sample_files = Dir.glob("**/*.#{language[:extension]}")
    sample_files.reject! { |file| excluded_paths.any? {|path| file.include? path }}
    sample_files.each do |sample_file|
      target = File.read(sample_file).scan(/\[START ([^\]]+)\]/).flatten.first
      language[:samples] << { "target" => target, "path" => sample_file }
    end
  end
end

manifest = {
  "version" => 1,
  "sets" => languages.map { |language|
    {
      "language"  => language[:name],
      "bin"       => language[:bin],
      "path"      => File.join(directory, "/"),
      "__items__" => language[:samples]
    }
  } 
}

puts manifest.to_yaml
