#! /bin/bash

if [ "$#" -ne 1 ]; then
  echo "Usage: ./script/test [folder with YAML test files]"
fi

TEST_DIR="$1"

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
TEST_SAMPLE_PY="$SCRIPT_DIR/pysampletester/sampletester"

echo $TEST_SAMPLE_PY -s $TEST_DIR/*.yaml
echo
$TEST_SAMPLE_PY -s $TEST_DIR/*.yaml
