// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go_gapic. DO NOT EDIT.

package main

import (
	"context"
	"flag"
	"fmt"
	"log"

	language "cloud.google.com/go/language/apiv1beta2"
	languagepb "google.golang.org/genproto/googleapis/cloud/language/v1beta2"
)

// [START language_analyze_sentiment_v1beta2]

func sampleAnalyzeSentiment(textContent string) error {
	ctx := context.Background()
	c, err := language.NewClient(ctx)
	if err != nil {
		return err
	}

	// textContent := "Example text for sentiment analysis"
	req := &languagepb.AnalyzeSentimentRequest{
		Document: &languagepb.Document{
			Source: &languagepb.Document_Content{
				Content: textContent,
			},
			Type: languagepb.Document_PLAIN_TEXT,
		},
	}
	resp, err := c.AnalyzeSentiment(ctx, req)
	if err != nil {
		return err
	}

	sentiment := resp.GetDocumentSentiment()
	fmt.Printf("Overall sentiment: %v\n", sentiment.GetScore())
	fmt.Printf("Sentiment for each sentence:\n")
	for _, sentence := range resp.GetSentences() {
		fmt.Printf("Sentence: %v\n", sentence.GetText().GetContent())
		fmt.Printf("=> %v\n", sentence.GetSentiment().GetScore())
	}
	return nil
}

// [END language_analyze_sentiment_v1beta2]

func main() {
	textContent := flag.String("textContent", "Example text for sentiment analysis", "")
	flag.Parse()
	if err := sampleAnalyzeSentiment(*textContent); err != nil {
		log.Fatal(err)
	}
}
