---
version: 1
sets:
- language: php
  bin: php
  path: speech/v1/
  __items__:
  - region_tag: speech_transcribe_async
    path: php/LongRunningRecognizeLongRunningRequestAsyncSpeechTranscribeAsync.php
  - region_tag: speech_transcribe_sync_gcs
    path: php/RecognizeRequestSpeechTranscribeSyncGcs.php
  - region_tag: speech_transcribe_sync
    path: php/RecognizeRequestSpeechTranscribeSync.php
  - region_tag: speech_transcribe_async_word_time_offsets_gcs
    path: php/RecognizeRequestSpeechTranscribeAsyncWordTimeOffsetsGcs.php
  - region_tag: speech_transcribe_async
    path: php/LongRunningRecognizeLongRunningRequestSpeechTranscribeAsync.php
- language: go
  bin: go run
  path: speech/v1/
  __items__:
  - region_tag: speech_transcribe_sync
    path: go/google.cloud.speech.v1.Speech_Recognize_speech_transcribe_sync.go
