// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go_gapic. DO NOT EDIT.

package main

import (
	"context"
	"flag"
	"fmt"
	"log"

	talent "cloud.google.com/go/talent/apiv4beta1"
	talentpb "google.golang.org/genproto/googleapis/cloud/talent/v4beta1"
)

// [START talent_create_company]

func sampleCreateCompany(projectId string, displayName string) error {
	ctx := context.Background()
	c, err := talent.NewCompanyClient(ctx)
	if err != nil {
		return err
	}

	// projectId := "Your Google Cloud Project ID"
	// displayName := "My Company Name"
	req := &talentpb.CreateCompanyRequest{
		Parent: fmt.Sprintf("projects/%s", projectId),
		Company: &talentpb.Company{
			DisplayName: displayName,
			ExternalId:  "Identifier of this company in my system",
		},
	}
	resp, err := c.CreateCompany(ctx, req)
	if err != nil {
		return err
	}

	fmt.Printf("Created company: %v\n", resp.GetDisplayName())
	fmt.Printf("Company name: %v\n", resp.GetName())
	return nil
}

// [END talent_create_company]

func main() {
	projectId := flag.String("project_id", "Your Google Cloud Project ID", "")
	displayName := flag.String("display_name", "My Company Name", "")
	flag.Parse()
	if err := sampleCreateCompany(*projectId, *displayName); err != nil {
		log.Fatal(err)
	}
}
