// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go_gapic. DO NOT EDIT.

package main

import (
	"context"
	"flag"
	"fmt"
	"log"

	talent "cloud.google.com/go/talent/apiv4beta1"
	"google.golang.org/api/iterator"
	talentpb "google.golang.org/genproto/googleapis/cloud/talent/v4beta1"
)

// [START talent_list_companies]

func sampleListCompanies(projectId string) error {
	ctx := context.Background()
	c, err := talent.NewCompanyClient(ctx)
	if err != nil {
		return err
	}

	// projectId := "Your Google Cloud Project ID"
	req := &talentpb.ListCompaniesRequest{
		Parent: fmt.Sprintf("projects/%s", projectId),
	}
	it := c.ListCompanies(ctx, req)
	for {
		resp, err := it.Next()
		if err == iterator.Done {
			break
		}
		if err != nil {
			return err
		}
		fmt.Printf("Company: %v\n", resp.GetName())
		fmt.Printf("Display name: %v\n", resp.GetDisplayName())
	}

	return nil
}

// [END talent_list_companies]

func main() {
	projectId := flag.String("project_id", "Your Google Cloud Project ID", "")
	flag.Parse()
	if err := sampleListCompanies(*projectId); err != nil {
		log.Fatal(err)
	}
}
